add initial implementation of resevervation get cmd
cloud-native-toolkit/itzcli pull request #12
Opened 2023-02-28 14:44 UTC by David-M-IBM

Created for [issue #414](https://zenhub.ibm.com/workspaces/tech-zone-accelerator-toolkit-627a5df0f8dae200104ff923/issues/skol/ocp-installer/414)

Usage: reservation get --reservation-id 63fcb95d9991b60017f119ea 

Output looks like:
![image](https://user-images.githubusercontent.com/83517881/221887708-ef9f009b-d5b4-4d1f-8c66-4a61288a0d0c.png)

2023-02-28 15:07 UTC, nathanagood requested changes
A couple minor points in the review here. The template changes would make the code

2023-02-28 15:07 UTC, nathanagood commented on cmd/getReservation.go
> +func getReservation(cmd *cobra.Command, args []string) error {
👍

2023-02-28 15:07 UTC, nathanagood commented on cmd/getReservation.go
>  		logger.Debug("Getting your reservation...")
Consider using `Debugf` and printing out the `reservationId` right here.

2023-02-28 15:16 UTC, David-M-IBM commented on pkg/reservations/base.go
> +func (w *TextWriter) WriteSingleRes(out io.Writer, rez TZReservation) error {
Kk updated this in latest commit.

2023-02-28 20:32 UTC, David-M-IBM commented on pkg/reservations/base.go
> +	for _, serviceLink := range rez.ServiceLinks {
I added this in the latest commit. Definitely think it looks a lot cleaner.

2023-03-01 20:43 UTC, nathanagood approved these changes
LGTM; nice changes.

2023-03-01 20:43 UTC, nathanagood commented on pkg/reservations/base.go
> +			{{- printf "\n    %s: ****Private****\n    --------------------------------" .Label}}
Nice!

2023-03-01 20:44 UTC, merged